apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tc02-hello-world
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Jdoe06/TC02-Kubernetes-Challenge.git
    targetRevision: main
    path: k8s/tc02-hello-world

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true